#!/usr/bin/env ruby
# -*- mode: ruby -*-

$LOAD_PATH.unshift File.join('.', 'lib')
$LOAD_PATH.unshift File.join('.', 'vendor/bundle')

require "octo_keeper"

Octokit.configure do |c|
  c.access_token = ENV['OCTOKEEPER_ACCESS_TOKEN']
  c.auto_paginate = true
end

OctoKeeper::Commands::CLI.start(ARGV)
